### ISSUE TITLE
[FR] Parameterize job lifespan

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-actions/filebrowser#7]

**Comment by asvetlov** [comment]
Sorry, I can recognize some words but not the whole sentence.

If it is a note for yourself to don't forget what to implement -- please assign yourself to the issue.
Otherwise, please elaborate.

**Comment by YevheniiSemendiak** [comment]
Sure, our team complaining that the filebrowser action uses default 1d lifespan. However, sometimes it is needed to change that behavior.
Therefore, I was thinking of adding one more input parameter into this action - `lifespan` with the default `1d` value.

**Comment by asvetlov** [comment]
Understood, thanks for the clarification.

**Comment by YevheniiSemendiak** [comment]
done in https://github.com/neuro-actions/filebrowser/pull/8
